### ISSUE TITLE
moviedata.csv is not available

### ISSUE THREAD

**Issue by hannah-ballard** [shubham1710/Movie-Recommendation-System#1]
The guide seems well written but the required file "moviedata.csv" is not available and it is unclear what steps are required to reproduce it.

**Comment by shubham1710** [comment]
Thanks for pointing out the issue Hannah. I have added the moviedata.csv file in the repository. You can view the data from there. Since the data is of around 22MB so Github won't be able to show it. Download the data in your system to view it and use it in your model. Right-click on view raw, and click on the save link as button to download it in CSV format.
